### ISSUE TITLE
Out of Bounds Write in v1.0.4

### ISSUE THREAD

**Issue by Halcy0nic** [landfillbaby/png2webp#3]
Hi!

While I was using the tool I had some fuzz tests running in the background and I think there might be an out of bounds write bug in the webp to png converter.  I compiled the tool from source using the default instructions/Makefile.  I can't exactly figure out from the backtrace where the out of bounds write is happening in png2webp.c, but a rough guess would be somewhere around:
https://github.com/landfillbaby/png2webp/blob/0c7119109cde91127a263bf0af252e5e730f7fba/png2webp.c#L499
https://github.com/landfillbaby/png2webp/blob/0c7119109cde91127a263bf0af252e5e730f7fba/png2webp.c#L504
https://github.com/landfillbaby/png2webp/blob/0c7119109cde91127a263bf0af252e5e730f7fba/png2webp.c#L505

I've attached the valgrind and gdb output below with a copy of the file used to trigger the issue:

<img width="879" alt="Screen Shot 2022-07-22 at 10 55 26 AM" src="https://user-images.githubusercontent.com/42481692/180489627-bcff9561-be97-4484-855e-bb97bced1ca2.png">

<img width="959" alt="Screen Shot 2022-07-22 at 11 36 28 AM" src="https://user-images.githubusercontent.com/42481692/180489642-1f1a90a2-1bf4-4dd9-b320-bf5012e5e7e3.png">

### Crash file
This would possibly allow an attacker to overwrite heap memory with attacker provided data.
[crash.zip](https://github.com/landfillbaby/png2webp/files/9169567/crash.zip)

**Comment by landfillbaby** [comment]
Thanks, I'll fix this ASAP

**Comment by landfillbaby** [comment]
What OS, architecture, and compiler were you testing on?

**Comment by landfillbaby** [comment]
I tested that file on a version I just compiled on Termux on my Pixel 6:

    $ png2webp -rv crash1_overflow.webp
    Decoding crash1_overflow.webp ...
    FORTIFY: read: count 18446744073709549715 > SSIZE_MAX
    Aborted

The problem seems to be that, against the C standard, certain platforms use `ssize_t` for `fread`'s parameters instead of `size_t`.
Try again using this patch, and when I'm at my PC I'll look into it further.

    diff --git a/png2webp.c b/png2webp.c
    index 42443f5..0261a0f 100644
    --- a/png2webp.c
    +++ b/png2webp.c
    @@ -319,6 +319,12 @@ static bool w2p(char *ip, char *op) {
       }
       size_t l = ((uint32_t)(i[4] | (i[5] << 8) | (i[6] << 16) | (i[7] << 24))) + 8;
       // ^ RIFF header size
    +#ifdef SSIZE_MAX
    +  if(l > SSIZE_MAX) {
    +    PF("ERROR reading %s: %s", IP, k[2]);
    +    goto w2p_close;
    +  }
    +#endif
       x = malloc(l);
       if(!x) {
         PF("ERROR reading %s: %s", IP, *k);

**Comment by landfillbaby** [comment]
wait hang on. that patch isn't right

**Comment by landfillbaby** [comment]
ok try it now

**Comment by landfillbaby** [comment]
I need to check this doesn't happen on platforms that don't define `SSIZE_MAX`, e.g. Windows.

**Comment by landfillbaby** [comment]
Also what fuzz tester are you using? I might use it myself

**Comment by landfillbaby** [comment]
Fixed in [v1.0.5](https://github.com/landfillbaby/png2webp/releases/tag/v1.0.5) (I think).
Won't close until you answer my questions though :)
I knew there was something up with my WebP reading code, thanks!

**Comment by landfillbaby** [comment]
@Halcy0nic feel free to add this to your trophy list lol 🥇

**Comment by Halcy0nic** [comment]
Sweet!  Just tested it out and it seems fixed.  Thanks again!

**Comment by Halcy0nic** [comment]
Also you are correct, the fuzzer I was using is AFL++ lol

**Comment by Halcy0nic** [comment]
I tested on a few Linux distros (Debian, ubuntu, etc), all 64 bit

**Comment by landfillbaby** [comment]
Ok good thank you :) I'll close this now
