### ISSUE TITLE
Please include license

### ISSUE THREAD

**Issue by T-Dynamos** [landfillbaby/png2webp#5]
Required for packaging

**Comment by landfillbaby** [comment]
it's now officially public domain. i even tagged a new release for you

**Comment by landfillbaby** [comment]
btw i'd love if i could just
`echo 'i dont care' > LICENSE` but that wouldn't have closed his issue

**Comment by T-Dynamos** [comment]
> btw i'd love if i could just `echo 'i dont care' > LICENSE` but that wouldn't have closed his issue

😂 Who cares about licence, Just need for packaging for Termux 
> `echo 'i dont care' > LICENSE`
Yes I believe that would also close the issue and I will just specify `TERMUX_PKG_LICENSE="custom"`

**Comment by T-Dynamos** [comment]
```
WTFPL - Do What The Fuck You Want To Public License can't be beat for blunt directness.
```
Also found this on https://unlicense.org

**Comment by landfillbaby** [comment]
yeah that's good too but something about having to attribute it to sam hocevar when it's supposed to be used as an anti-copyright notice rubbed me the wrong way
`TERMUX_PKG_LICENSE="Unlicense"` is fine :)

**Comment by landfillbaby** [comment]
i change my mind! fuck licenses
